version: "3.7"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /web:/web
    networks:
      lnmp:
        ipv4_address: 10.5.0.2

  php:
    build: ./php71
    ports:
      - "9001:9000"
      - "5001:22"
    links:
      - "mysql"
      - "redis"
    #    - "memcached"
    volumes:
      - /web:/web
    environment:
      MYSQL_PORT: 3306
      REDIS_PORT: 6379
    networks:
      lnmp:
        ipv4_address: 10.5.0.3
    extra_hosts:
      - "base.local:10.5.0.2"

  mysql:
    build: ./mysql
    ports:
      - "5306:3306"
    volumes:
      - /web/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      lnmp:
        ipv4_address: 10.5.0.4


  redis:
    build: ./redis
    command: redis-server --requirepass 123456
    ports:
      - "6369:6379"
    networks:
      lnmp:
        ipv4_address: 10.5.0.5


networks:
  lnmp:
    driver: bridge
    ipam:
      config:
          - subnet: 10.5.0.0/16
#            gateway: 10.5.0.1

#
#memcached:
#  build: ./memcached
#  ports:
#    - "11211:11211"
